# Generated by Django 3.2.9 on 2021-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='released_date',
        ),
        migrations.AddField(
            model_name='film',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='released_year',
            field=models.IntegerField(default=0),
        ),
    ]
