# Generated by Django 3.2.9 on 2021-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_film_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='released_year',
            field=models.IntegerField(),
        ),
    ]
