# Generated by Django 3.2.9 on 2021-12-18 06:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_film_released_year'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('mostpopular', django.db.models.manager.Manager()),
            ],
        ),
    ]
