# Generated by Django 3.2.9 on 2021-12-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_film_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
            ],
        ),
    ]
